#!/usr/bin/env bash
# src/bash/dnsresolvh
# =============================================================================
# DNS Resolver Daemon (dnsresolvd). Version 0.1
# =============================================================================
# A daemon that performs DNS lookups for the given hostname
# passed in an HTTP request, with the focus on its implementation
# using various programming languages. (Netcat-boosted impl.)
# =============================================================================
# Copyright (C) 2017-2019 Radislav (Radicchio) Golubtsov
#
# (See the LICENSE file at the top of the source tree.)
#

# Helper function. Draws a horizontal separator banner.
_separator_draw() { banner_text=$1 # <== C-ished "(const char *banner_text)":-)
    i=${#banner_text} # <== C-ished "unsigned char i = strlen(banner_text);":-)

    while ((i > 0)); do echo -n '='; let i--; done; echo
}

# Helper constants.
declare -r _EXIT_FAILURE=1 #    Failing exit status.
declare -r _EXIT_SUCCESS=0 # Successful exit status.
declare -r _EMPTY_STRING=""
declare -r _COMMA=","
declare -r _PRINT_BANNER_OPT="-V"

# Daemon name, version, and copyright banners. */
declare -r _DMN_NAME="DNS Resolver Daemon (dnsresolvd)"
declare -r _DMN_DESCRIPTION="Performs DNS lookups for the given hostname "`
                           `"passed in an HTTP request"
declare -r _DMN_VERSION_S__="Version"
declare -r _DMN_VERSION="0.1"
declare -r _DMN_COPYRIGHT__="Copyright (C) 2017-2019"
declare -r _DMN_AUTHOR="Radislav Golubtsov <ragolubtsov@my.com>"

# vim:set nu et ts=4 sw=4:
